# Generated by Django 2.0 on 2021-05-15 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_doctor', models.CharField(max_length=200)),
                ('type_doctor', models.CharField(choices=[('General Physicians', 'General Physicians'), ('Pediatricians', 'Pediatricians'), ('General Surgeon', 'General Surgeon'), ('Cardiologist', 'Cardiologist'), ('Dentist', 'Dentist'), ('ENT Specialist', 'ENT Specialist'), ('Gynecologist', 'Gynecologist'), ('Dermatologists', 'Dermatologists')], max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('adress', models.CharField(max_length=500)),
                ('relation_patient', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsapp.Doctor')),
            ],
        ),
    ]
