# Generated by Django 2.0 on 2021-05-16 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0002_auto_20210516_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 6, 37, 22, 716688, tzinfo=utc)),
        ),
    ]
