# Generated by Django 2.0 on 2021-05-16 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0003_auto_20210516_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'patients', 'verbose_name_plural': 'patients'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 6, 50, 6, 166355, tzinfo=utc)),
        ),
    ]
