# Generated by Django 2.0 on 2021-05-16 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0005_auto_20210516_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 11, 1, 36, 269370, tzinfo=utc)),
        ),
    ]
