# Generated by Django 3.2.3 on 2021-05-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0007_alter_doctor_time'),
    ]

    operations = [
    ]
