# Generated by Django 3.2.3 on 2021-05-18 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0008_auto_20210518_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 7, 31, 21, 763244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patients',
            name='disease',
            field=models.CharField(db_column='illness', max_length=200),
        ),
    ]
